window.sentlog=window.sentlog||{referrer:!1};window.site_name=window.site_name||"58";var json_trackPagetype="NA",json_trackURL="NA",json_trackParams="NA",json_trackPageview="NA";"undefined"!=typeof ____json4fe&&("_trackPagetype"in ____json4fe&&(json_trackPagetype=____json4fe._trackPagetype),"_trackURL"in ____json4fe&&(json_trackURL=____json4fe._trackURL),"_trackParams"in ____json4fe&&(json_trackParams=____json4fe._trackParams),"_trackPageview"in ____json4fe&&(json_trackPageview=____json4fe._trackPageview));
window.tgreg=window.tgreg||-1;window._trackURL=window._trackURL||json_trackURL||"NA";window._trackParams=window._trackParams||json_trackParams||"NA";var referrer=encodeURIComponent(document.referrer),pagetypeTmp,post_countTmp;if("NA"!=_trackURL){var trackJsonStr=eval("("+_trackURL+")");trackJsonStr.pagetype&&(pagetypeTmp=trackJsonStr.pagetype);trackJsonStr.post_count&&(post_countTmp=trackJsonStr.post_count)}window.page_type=window.page_type||pagetypeTmp||json_trackPagetype||"NA";
window.post_count=window.post_count||post_countTmp||-1;if("NA"!=json_trackPageview)if("NA"!=_trackURL){var tmpArr=_trackURL.split("{");_trackURL=tmpArr[0]+"{'GA_pageview':'"+json_trackPageview+"',"+tmpArr[1]}else _trackURL="{'GA_pageview':'"+json_trackPageview+"'}";
if("NA"!=_trackURL&&-1!=_trackURL.indexOf("GA_pageview")&&"list"!=page_type&&"post"!=page_type)try{window._gaq=window._gaq||[];window._gaq.push(["pageTracker._setAccount","UA-877409-4"]);window._gaq.push(["pageTracker._setDomainName",".58.com"]);window._gaq.push(["pageTracker._setAllowLinker",!0]);window._gaq.push(["pageTracker._addOrganic","sogou","query"]);window._gaq.push(["pageTracker._addOrganic","baidu","word"]);window._gaq.push(["pageTracker._addOrganic","soso","w"]);window._gaq.push(["pageTracker._addOrganic",
"youdao","q"]);window._gaq.push(["pageTracker._addOrganic","360","q"]);window._gaq.push(["pageTracker._trackPageLoadTime"]);-1!=_trackURL.indexOf("'GA_pageview':''")?window._gaq.push(["pageTracker._trackPageview"]):(trackJsonStr=eval("("+_trackURL+")"),trackJsonStr.GA_pageview&&(ga_pageviewStr=trackJsonStr.GA_pageview,window._gaq.push(["pageTracker._trackPageview",ga_pageviewStr])));var ga_protocol="https:"==document.location.protocol?" https://ssl":" http://www",sNode=document.createElement("script");
sNode.type="text/javascript";sNode.src=ga_protocol+".google-analytics.com/ga.js";document.getElementsByTagName("body")[0].appendChild(sNode)}catch(e_ga){}var GTID=Math.random(),GTID=(new Date).valueOf()+""+GTID,ClickID=0,curURL=window.location.href;"NA"==_trackURL?_trackURL="{'GTID':'"+GTID+"'}":(tmpArr=_trackURL.split("{"),_trackURL=tmpArr[0]+"{'GTID':'"+GTID+"',"+tmpArr[1]);
$("a").bind("click",function(){ClickID+=1;if("NO"==filterList(curURL)&&-1!=curURL.indexOf(".58.com")){var a=$(this).attr("href")||"#";-1!=a.indexOf("javascript:")||"#"==a.substring(0,1)||"NO"!=filterList(a)||"/"!=a.substring(0,1)&&-1==a.indexOf(".58.com")||(a.match(/[\?&]PGTID=[^&]*&ClickID=\d*/)?$(this).attr("href",a.replace(/PGTID=[^&]*&ClickID=\d*/,"PGTID="+GTID+"&ClickID="+ClickID)):$(this).attr("href",a.trim()+(-1==a.indexOf("?")?"?":"&")+"PGTID="+GTID+"&ClickID="+ClickID))}});
$("[tongji_id]").bind("click",function(a){var b=a.srcElement?a.srcElement:a.target;"A"==b.tagName.toUpperCase()&&(a=$(b).attr("href")||"#",b=$(b).text(),-1==a.indexOf("javascript:")&&"#"!=a.substring(0,1)&&clickLog("from="+$(this).attr("tongji_id")+"&text="+encodeURIComponent(b)+"&to="+encodeURIComponent(a)))});(function(){$("[tongji_tag]").bind("click",function(){var a=$(this).attr("tongji_tag");clickLog("from="+a)})})();
(function(){-1!=(_trackURL||"NA").indexOf("'pagetype':'home'")&&$("[href]").bind("click",function(a){var b=$(this).attr("href"),c=$(this).offset().top,d=$(this).offset().left;clickLog("from=heatmap:"+b+"&tagX="+d+"&tagY="+c+"&mouseX="+a.pageX+"&mouseY="+a.pageY)})})();
if(-1!=curURL.indexOf("post.58.com")||!sentlog.referrer){_trackParams=format_trackParams(_trackParams);_trackParams=encodeURIComponent(_trackParams);var logmsg="tag=pvstatall&referrer="+referrer+"&type="+page_type+"&post_count="+post_count+"&_trackParams="+_trackParams;if("detail"==page_type||"jianli_detail"==page_type)try{logmsg=logmsg+"&userid="+____json4fe.userid,"phone"in ____json4fe&&(logmsg=logmsg+"&huzhuan="+____json4fe.phone),0<tgreg&&(logmsg=logmsg+"&tgreg="+tgreg)}catch(e$$14){}try{if("version"in
____json4fe&&(logmsg=logmsg+"&version="+____json4fe.version),"smsc"in ____json4fe&&(logmsg=logmsg+"&smsc="+____json4fe.smsc),"start"in ____json4fe&&(logmsg+="&loadtime="+((new Date).getTime()-____json4fe.start)),"supplycount"in ____json4fe)for(var attr in ____json4fe.supplycount)logmsg=logmsg+"&supplycount."+attr+"="+____json4fe.supplycount[attr]}catch(e$$15){}try{logmsg=logmsg+"&window_size="+document.documentElement.clientWidth+"x"+document.documentElement.clientHeight}catch(e$$16){}try{var m_ga_utma=
getcookie("__utma");m_ga_utma&&""!=m_ga_utma&&(logmsg=logmsg+"&_ga_utma="+m_ga_utma);var init_refer=referrer,cookie_init_refer=getcookie("init_refer"),cookie_new_session=getcookie("new_session");cookie_new_session&&""!=cookie_new_session?(setcookie_session("new_session","0"),setcookie_session("init_refer",cookie_init_refer),"NA"!=_trackURL?(tmpArr=_trackURL.split("{"),_trackURL=tmpArr[0]+"{'new_session':'0','init_refer':'"+cookie_init_refer+"',"+tmpArr[1]):_trackURL="{'new_session':'0','init_refer':'"+
cookie_init_refer+"'}"):(setcookie_session("new_session","1"),setcookie_session("init_refer",init_refer),"NA"!=_trackURL?(tmpArr=_trackURL.split("{"),_trackURL=tmpArr[0]+"{'new_session':'1','init_refer':'"+init_refer+"',"+tmpArr[1]):_trackURL="{'new_session':'1','init_refer':'"+init_refer+"'}")}catch(e$$17){}"NA"!=_trackURL&&(logmsg=logmsg+"&trackURL="+_trackURL);ajaxlog_new(logmsg);try{var cnzz_protocol="https:"==document.location.protocol?" https://":" http://",sNode=document.createElement("script");
sNode.type="text/javascript";sNode.src=cnzz_protocol+"w.cnzz.com/c.php?id=30017898";document.getElementsByTagName("head")[0].appendChild(sNode)}catch(e_cnzz){}sentlog.referrer=!0}function setcookie(a,b,c){var d=new Date;d.setTime(d.getTime()+864E5*c);document.cookie=a+"="+escape(b)+"; expires="+d.toGMTString()+"; domain=.58.com; path=/"}
function setcookie_session(a,b){var c=new Date;c.setTime(c.getTime()+18E5);document.cookie=a+"="+escape(b)+"; expires="+c.toGMTString()+"; domain=.58.com; path=/"}function getcookie(a){var b;return(b=document.cookie.match(RegExp("(^| )"+a+"=([^;]*)(;|$)")))?unescape(b[2]):""}function ajaxsend(a){(new Image).src=a}
function ajaxlog(a){ajaxsend(document.location.protocol+"//track.58.com/empty.js.gif?site_name="+site_name+"&"+a+"&rand="+Math.random());ajaxsend(document.location.protocol+"//tracklog.58.com/pc/empty.js.gif?site_name="+site_name+"&"+a+"&rand="+Math.random())}
function ajaxlog_new(a){var b=Math.random();ajaxsend(document.location.protocol+"//tracklog.58.com/pc/empty.js.gif?fromid=referrer2&site_name="+site_name+"&"+a+"&rand_id="+b);var c=_trackURL||"NA";if(-1!=c.indexOf("'pagetype':'detail'")||-1!=c.indexOf("'pagetype':'jianli_detail'"))-1==c.indexOf("'cate':'9224")&&-1==c.indexOf("'cate':'9225")&&-1==c.indexOf("'cate':'13941")&&-1==c.indexOf("'cate':'13952")||ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=PCTrack&"+a+"&rand_id="+
b)}function ajaxlog2(a){ajaxlog(a)}function ajaxlogr(a){ajaxsend(document.location.protocol+"//tracklog.58.com/pc/click/listclicklog?site_name="+site_name+"&"+a+"&trackURL="+_trackURL+"&ClickID="+ClickID+"&referrer="+referrer+"&rand="+Math.random())}function format_trackParams(a){if("NA"==a)return a;try{for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c].I+":"+a[c].V.replace(/\|/g,"*"));return b.join("@@")}catch(e){return"error"}}
function clickLog(a){var b=getcookie("bangbangid");b&&""!=b||(b="");ajaxsend(document.location.protocol+"//tracklog.58.com/pc/click/empty.js.gif?site_name="+site_name+"&tag=pvsiters&"+a+"&trackURL="+_trackURL+"&ClickID="+ClickID+"&bangbangid="+b+"&referrer="+referrer+"&rand="+Math.random());-1!=a.indexOf("&ROI=")&&ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=PCClick&"+a+"&trackURL="+_trackURL+"&ClickID="+ClickID+"&bangbangid="+b+"&referrer="+referrer+"&rand="+Math.random())}
function showLog(a){}function filterList(a){var b=".58.com.cn portal.58.com post.58.com 5858.com lieche.58.com dict.58.com/xiaoqu".split(" "),c;for(c in b)if(-1!=a.indexOf(b[c]))return"YES";return"NO"};
